### ISSUE TITLE
Update Elixir docs

### ISSUE THREAD

**Issue by yazfaz** [opentelemetry-beam/opentelemetry_exporter#3]
The Elixir release config needs a few minor typos fixed.  I ran into issues setting up this package as I'm not as familiar with Erlang. 

I can open up a PR with these changes to help others using this for their Elixir apps, but I don't have permission to push to this repo.

Changes to be made to the README:
```elixir
  config :opentelemetry,
    :processors, ot_batch_processor: %{exporter: {:opentelemetry_exporter, %{endpoints: [{:http, 
    'localhost', 9090, []}]}}}
```

**Comment by tsloughter** [comment]
@yazfaz thanks! Sorry I missed this. Turns out I wasn't watching my repo! :)

Yes, please open a PR, you can fork this repo to open a PR from your own fork to this repo.

**Comment by tsloughter** [comment]
@yazfaz I've updated the readme in my PR #4 

Let me know if I missed anything.
